name: .NET Desktop CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ApiGateWayMicroService
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.100-preview.7'  # Utilisez la version .NET appropriée

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Publish
      run: dotnet publish -c Release -o out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to production
      uses: some-deployment-action
      with:
        api-key: ${{ secrets.DEPLOYMENT_API_KEY }}
