name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
 build-and-deploy:
    runs-on: self-hosted
    steps:
        - name: Pull Data from main branch
          uses: actions/checkout@v2
  
        - name: Build Docker images
          run: |
            sudo docker-compose -f docker-compose.yml build 
            sudo docker save apigateway-app > apigateway-app.tar 

        - name: Install sshpass
          run: sudo apt-get install -y sshpass
        - name: Transfer Docker Image to Server
          run: |
            sshpass -p ${{ secrets.SSH_PASSWORD }} scp -o StrictHostKeyChecking=no apigateway-app.tar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/root/
          env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        - name: Load Docker Image on Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port:  ${{ secrets.SSH_PORT }}
            script: |
              ./deployApigateway.sh
              
        - name: Remove Docker Images
          run: sudo docker image prune -a -f
